// <auto-generated />
namespace AutoCareInc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _202002070317420 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202002070317420));
        
        string IMigrationMetadata.Id
        {
            get { return "202002070531381_202002070317420"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
